<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1vn5cx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1vn5cx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX1vn5cx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX1vn5cx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX1vn5cx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'X1vn5cx',
    'container.build_id' => '43bb1459',
    'container.build_time' => 1531474582,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1vn5cx');
